apiVersion: apps/v1
kind: Deployment
metadata:
  name: creditcheckservice
spec:
  selector:
    matchLabels:
      app: creditcheckservice
  template:
    metadata:
      labels:
        app: creditcheckservice
    spec:
      tolerations:
      nodeSelector:
      terminationGracePeriodSeconds: 5
      containers:
      - name: creditcheckservice
        image: docker.io/library/credit-check-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8888
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_SERVICE_NAME
          value: creditcheckservice
        - name:  OTEL_PROPAGATORS
          value: "tracecontext,baggage,b3multi"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: 'http://$(NODE_IP):4317'
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: 'deployment.environment=qep-creditflow,service.version=2.0'
        - name: PORT
          value: "8888"
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        resources:
          requests:
            cpu: 110m
            memory: 90Mi
          limits:
            cpu: 130m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: creditcheckservice
spec:
  type: NodePort
  selector:
    app: creditcheckservice
  ports:
  - name: http
    port: 8888
    targetPort: 8888
